import { Navigate, NavLink, Outlet, Route, Routes, useParams } from 'react-router-dom';
import { AppWindow, CalendarClock, Cloud, LayoutDashboard, ListVideo, Monitor, Play, Plus, Settings, Sparkles, Wifi, WifiOff } from 'lucide-react';

const nav=[['/dashboard','Visão geral',LayoutDashboard],['/conteudo','Conteúdo',AppWindow],['/playlists','Playlists',ListVideo],['/programacoes','Programações',CalendarClock],['/telas','Telas',Monitor],['/apps','PontoView Apps',Sparkles]] as const;
function Shell(){return <div className="shell"><aside><div className="brand"><b>P</b><span><strong>PontoView</strong><small>Screens</small></span></div><nav>{nav.map(([to,label,Icon])=><NavLink key={to} to={to} className={({isActive})=>isActive?'active':''}><Icon size={18}/><span>{label}</span></NavLink>)}</nav><NavLink className="settings" to="/configuracoes"><Settings size={18}/><span>Configurações</span></NavLink></aside><main><header><div><small>PontoView Screens</small><strong>Gerencie sua comunicação em um só lugar.</strong></div><span className="ok">● Sistema operacional</span></header><div className="page"><Outlet/></div></main></div>}
const cards=[['Telas online','3','de 4 telas',Monitor],['Conteúdos','18','12 do Google Drive',Cloud],['Playlists','5','3 em exibição',Play],['Programações','4','2 ativas agora',CalendarClock]] as const;
function Dashboard(){return <><Head eyebrow="Visão geral" title="Boa tarde." text="Acompanhe suas telas, conteúdos e programações." action="Conectar tela"/><div className="stats">{cards.map(([l,v,m,I])=><article key={l}><I size={19}/><span>{l}</span><strong>{v}</strong><small>{m}</small></article>)}</div><div className="grid"><section className="panel"><h2>Telas</h2><p>Status dos dispositivos conectados</p>{[['Recepção principal',true],['Sala de espera',true],['Refeitório',true],['Auditório',false]].map(([n,o])=><div className="screen" key={String(n)}><Monitor size={19}/><span><b>{n}</b><small>Recepção Geral</small></span><em className={o?'online':'offline'}>{o?<Wifi size={14}/>:<WifiOff size={14}/>} {o?'Online':'Offline'}</em></div>)}</section><section className="panel now"><small>EM EXIBIÇÃO</small><h2>Recepção Geral</h2><p>3 telas usando esta playlist</p><div className="bar"><i/></div><span>Próximo: Previsão do tempo</span></section></div></>}
function Head({eyebrow,title,text,action}:{eyebrow:string,title:string,text:string,action?:string}){return <div className="head"><div><small>{eyebrow}</small><h1>{title}</h1><p>{text}</p></div>{action&&<button><Plus size={16}/>{action}</button>}</div>}
function Placeholder({kind,title,text}:{kind:string,title:string,text:string}){return <><Head eyebrow={kind} title={title} text={text} action={title==='Configurações'?undefined:`Novo ${title.toLowerCase()}`}/><div className="placeholder"><h2>{title}</h2><p>Estrutura inicial pronta para receber dados reais do Supabase.</p></div></>}
function Player(){const {screenId}=useParams();return <div className="player"><small>PontoView Player</small><strong>{screenId}</strong><span>Aguardando sincronização da playlist</span></div>}
export default function App(){return <Routes><Route path="/player/:screenId" element={<Player/>}/><Route path="/" element={<Shell/>}><Route index element={<Navigate to="/dashboard" replace/>}/><Route path="dashboard" element={<Dashboard/>}/><Route path="conteudo" element={<Placeholder kind="Biblioteca" title="Conteúdo" text="Mídias do Google Drive, páginas web e conteúdos PontoView."/>}/><Route path="playlists" element={<Placeholder kind="Organização" title="Playlists" text="Combine mídias e apps na ordem de exibição."/>}/><Route path="programacoes" element={<Placeholder kind="Automação" title="Programações" text="Defina dias, horários e campanhas temporárias."/>}/><Route path="telas" element={<Placeholder kind="Dispositivos" title="Telas" text="Gerencie players, conectividade e pareamento."/>}/><Route path="apps" element={<Placeholder kind="Conteúdo dinâmico" title="PontoView Apps" text="Painéis prontos para adicionar às playlists."/>}/><Route path="configuracoes" element={<Placeholder kind="Conta" title="Configurações" text="Empresa, usuários, integrações e preferências."/>}/></Route></Routes>}
